export enum ActivityName {
  CATEGORY = 'CATEGORY',
  CONTENT = 'CONTENT',
  ROLE = 'ROLE',
  USER = 'USER',
  CONTENT_COMMENT = 'CONTENT_COMMENT',
}

export enum ActivityType {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  SOFT_DELETE = 'SOFT_DELETE',
  DELETED = 'DELETED',
  VERIFICATION = 'VERIFICATION',
  PASSWORD_UPDATED = 'PASSWORD_UPDATED',
  INVITED = 'INVITED',
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  COMPLETED = 'COMPLETED',
  SENT = 'SENT',
  PENDING = 'PENDING',
  ALLOCATED = 'ALLOCATED',
  TRANSFERRED = 'TRANSFERRED',
  REPLY = 'REPLY',
  SEND = 'SEND',
  JOINED = 'JOINED',
}
