export const collectionNames = {
  user: 'users',
  category: 'categories',
  subCategory: 'sub-categories',
  channel: 'channels',
  content: 'contents',
  contenType: 'contenttypes',
  contentComment: 'content-comments',
  councilor: 'councilor',
  councilorAppoinment: 'councilor-appoinments',
  restaurant: 'restaurant',
  restaurantBooking: 'restaurant-bookings',
  restaurantMenu: 'restaurant-menus',
  restaurantCatogory: 'restaurant-categories',
};
